---
- hosts: myhosts
  become: yes
  tasks:
    - name: Create folder for Apache Kafka
      command: mkdir -p ~/homework/ansible/kafka
    - name: Unpack downloaded files
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/kafka/4.0.0/kafka-4.0.0-src.tgz
        dest: ~/homework/ansible/kafka
        remote_src: yes
